# Generated by Django 4.0.6 on 2022-08-01 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link_shorter', '0002_baba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='baba',
        ),
    ]
